// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6ZVaw8G8K4tDImh3ZbgJn8abYEG9qa8',
    appId: '1:393004266671:web:4dbceb9231d8854a26105a',
    messagingSenderId: '393004266671',
    projectId: 'fcm090-e803d',
    authDomain: 'fcm090-e803d.firebaseapp.com',
    storageBucket: 'fcm090-e803d.firebasestorage.app',
    measurementId: 'G-Z36C65QE0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANUq7TeiZKY5MwPggMRnA3cBj39xroiK8',
    appId: '1:393004266671:android:4d7d3170cb07d8cc26105a',
    messagingSenderId: '393004266671',
    projectId: 'fcm090-e803d',
    storageBucket: 'fcm090-e803d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ZLi-PxMGM7nYhCT12OSswFFU31KZGxE',
    appId: '1:393004266671:ios:e35a54eec48ea3f826105a',
    messagingSenderId: '393004266671',
    projectId: 'fcm090-e803d',
    storageBucket: 'fcm090-e803d.firebasestorage.app',
    iosBundleId: 'com.example.fcmProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ZLi-PxMGM7nYhCT12OSswFFU31KZGxE',
    appId: '1:393004266671:ios:e35a54eec48ea3f826105a',
    messagingSenderId: '393004266671',
    projectId: 'fcm090-e803d',
    storageBucket: 'fcm090-e803d.firebasestorage.app',
    iosBundleId: 'com.example.fcmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa6ZVaw8G8K4tDImh3ZbgJn8abYEG9qa8',
    appId: '1:393004266671:web:ec4d89a3ef11c27126105a',
    messagingSenderId: '393004266671',
    projectId: 'fcm090-e803d',
    authDomain: 'fcm090-e803d.firebaseapp.com',
    storageBucket: 'fcm090-e803d.firebasestorage.app',
    measurementId: 'G-MDD31RLK77',
  );
}
